name: Designhaus Studio Inc
favicon: null
layout_spectrum: 0.9341044968459755
typography_spectrum: 0.96462
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#21201e'
    - '#808185'
    - '#5f5e5d'
    - '#c0c0c1'
  brandStrength: 0.8125
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
