name: Designhaus Studio Inc
favicon: null
layout_spectrum: 0.9341044968459755
typography_spectrum: 0.8318459938745946
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#21201e'
    - '#808185'
    - '#5f5e5d'
    - '#c0c0c1'
  brandStrength: 0.3427681678440422
  lightness: 0.45213562180288136
  saturation: 0.9251479094382375
  rhythmicContrast: 0.21623739739879966
purpose: []
